#!/bin/sh

# combines all the config parts into a single config file.
# doing this instead of using `import` because `import`
# does not carry over variables

P="$HOME/.config/i3"
files=( apps defaults shortcuts visual startup local forwindow )

rm $P/config
for f in "${files[@]}"; do
	cat $P/$f >> $P/config
done

i3 reload
