[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-gcc-ar"

[target.aarch64-linux-android]
ar = ".cargo/android-ndk/arm64/bin/aarch64-linux-android-ar"
linker = ".cargo/android-ndk/arm64/bin/aarch64-linux-android-clang"

[target.armv7-linux-androideabi]
ar = ".cargo/android-ndk/arm/bin/arm-linux-androideabi-ar"
linker = ".cargo/android-ndk/arm/bin/arm-linux-androideabi-clang"

[target.i686-linux-android]
ar = ".cargo/android-ndk/x86/bin/i686-linux-android-ar"
linker = ".cargo/android-ndk/x86/bin/i686-linux-android-clang"