[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-gcc-ar"

[target.aarch64-linux-android]
ar = "${ANDROID_NDK_CARGO}/arm64/bin/aarch64-linux-android-ar"
linker = "${ANDROID_NDK_CARGO}/arm64/bin/aarch64-linux-android-clang"

[target.armv7-linux-androideabi]
ar = "${ANDROID_NDK_CARGO}/arm/bin/arm-linux-androideabi-ar"
linker = "${ANDROID_NDK_CARGO}/arm/bin/arm-linux-androideabi-clang"

[target.i686-linux-android]
ar = "${ANDROID_NDK_CARGO}/x86/bin/i686-linux-android-ar"
linker = "${ANDROID_NDK_CARGO}/x86/bin/i686-linux-android-clang"