#!/bin/sh

# this looks for a file called commit-notes in the root of the repository
# and includes it in the commit body, so you can keep track of changes
# as you work on them and have them automatically pulled into the commit
# message.

if [ -f "$HOME/.gitmessage" ]; then
	cat $HOME/.gitmessage > "$1"
else
	echo "" > "$1"
fi

if [ -f "commit-notes" ]; then
	echo "\n# -= imported from 'commit-notes' =-\n" >> "$1"
	while read line; do
		echo "#$line" >> "$1"
	done < commit-notes
fi

# this checks for all other angular like commits in the gitlog and shows the ones
# that have already been used for consitency

echo "\n# -= previously used angular commit headers =-" >> "$1"
git log --pretty=oneline --abbrev-commit | python .git/hooks/get-angular-types.py >> "$1"
