"plugins
call plug#begin()
Plug 'rust-lang/rust.vim'
Plug 'majutsushi/tagbar'
Plug 'vim-syntastic/syntastic'
Plug 'airblade/vim-gitgutter'
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
call plug#end()

" display stuff
set number
set nowrap
set ruler

set encoding=utf-8

" formatting preferences
set tabstop=4
set shiftwidth=4
set expandtab

" mouse
set mouse=a

" PLUGIN : TAGBAR CONFIGURATION
nmap <F8> :TagbarToggle<CR>
